### ISSUE TITLE
fail to buid

### ISSUE THREAD

**Issue by marcussacana** [Inori/Xp3Viewer-AfterStory#1]
![fail](https://cloud.githubusercontent.com/assets/10576957/6601129/9a9b0efc-c7f2-11e4-96de-535cc147d078.png)
fail to compile here...
and what are the necessary dependencies?
if possible tell me the command line this tool?

**Comment by Inori** [comment]
I was just starting to write this tool a few days ago, so it can not work now. You don't have to build it.

发自我的 Windows Phone

---

发件人: marcussacanamailto:notifications@github.com
发送时间: ‎2015/‎3/‎12 上午 12:31
收件人: Inori/Xp3Viewer-AfterStorymailto:Xp3Viewer-AfterStory@noreply.github.com
主题: [Xp3Viewer-AfterStory] fail to buid (#1)

![fail](https://cloud.githubusercontent.com/assets/10576957/6601129/9a9b0efc-c7f2-11e4-96de-535cc147d078.png)
fail to compile here...
and what are the necessary dependencies?
if possible tell me the command line this tool?

---

Reply to this email directly or view it on GitHub:
https://github.com/Inori/Xp3Viewer-AfterStory/issues/1

**Comment by marcussacana** [comment]
okay.... you can comment here on relase this tool?....
Thanks for help man

**Comment by sgqy** [comment]
You opened the file (codepage: 936 / zh-CN) in codepage 932 / ja-JP
Because of this, some EOL is not identified
You can convert the file from 936 to Unicode and retry

**Comment by marcussacana** [comment]
thanks... i try later... the inori says the tool is incomplete....
and @Inori this tool on complete can support the KrKrZ engine (for nekopara)

**Comment by marcussacana** [comment]
@Inori this project is finenshed or i can use now?
and for now the afterstory support KrKrZ?

**Comment by Inori** [comment]
No it's not finished

发自我的 Windows Phone

---

发件人: marcussacanamailto:notifications@github.com
发送时间: ‎2015/‎6/‎25 上午 6:45
收件人: Inori/Xp3Viewer-AfterStorymailto:Xp3Viewer-AfterStory@noreply.github.com
抄送: Fuyinmailto:bingkan@outlook.com
主题: Re: [Xp3Viewer-AfterStory] fail to buid (#1)

@Inori this project is finenshed or i can use now?
and for now the afterstory support KrKrZ?

---
